name: academ_gora_release
description: A new Flutter project.

version: 1.1.3+15

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  shared_preferences: ^2.0.7
  flutter_auth_ui: ^2.3.2
  firebase_database: 7.1.1
  firebase_storage: ^10.0.4
  flutter_calendar_carousel: ^2.0.3
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.10
  flutter_email_sender: ^5.0.2
  flutter_phone_direct_caller: ^2.0.0
  expandable: ^5.0.1
  image_picker: ^0.8.4+1
  expand_tap_area: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  cached_network_image: ^3.2.0
  flutter_local_notifications: ^9.1.5
  timezone: ^0.8.0
  firebase_messaging: ^11.2.3
  dio: ^4.0.4
  date_format: ^2.0.5
# script for uploading app icon: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"

























  


flutter:

  uses-material-design: true
  assets:
    - assets/main/
    - assets/
    - assets/auth/
    - assets/registration_to_instructor/
    - assets/instructors_list/
    - assets/registration_parameters/
    - assets/reg_final/
    - assets/profile/
    - assets/all_instructors/
    - assets/instructor_profile/
    - assets/instructor_profile/social_network_icons/
    - assets/info_screens/
    - assets/info_screens/call_us/
    - assets/info_screens/prices/
    - assets/info_screens/about_us/
    - assets/info_screens/chill_zone/
    - assets/instructor_set_time/