import 'package:flutter/material.dart';

const kBlack = Color(0xFF313131);
const kBlackLight = Color(0xFF4B5664);
const kViolet = Color(0xFF6E62E4);
const kVioletPale = Color(0xFFF9F9FE);
const kVioletVeryPale = Color(0xFFF6F6FD);
const kDarkGrey = Color(0xFFEBEAFB);
const kGrey = Color(0xFFF6F6FD);
const kLightGrey = Color(0xFFE3E1EA);
const kRectangleGrey = Color(0xFFE8EAEC);
const kWhite = Color(0xFFFFFFFF);
const kTrans = Colors.transparent;
const kBlueLight = Color(0xFFE4F3FE);
const kBlue = Color(0xFFC7E6FF);
const kDarkBlue = Color(0xFF5DB0E7);
const kDarkBlueOpacity = Color(0xFFc6e1f6);
const kChartBlue = Color(0xFFD8E4FF);
const kRed = Color(0xFFBE0202);
const kDarkViolet = Color(0xFF3A3379);